audio:
  sample_rate: 16000
  channels: 1
  chunk_duration: 30  # 30 seconds for testing (instead of 5 minutes)
  device_id: null
  silence_threshold: 0.02  # Higher threshold to avoid false silence detection
  silence_duration: 5.0    # Longer silence before segmenting

transcription:
  provider: "local"
  model_size: "tiny"  # Fastest model for testing
  language: "en"
  compute_type: "float32"
  device: "auto"
  beam_size: 5
  temperature: 0.0

summary:
  provider: "claude"
  model: "claude-3-haiku-20240307"
  max_tokens: 500
  temperature: 0.3
  daily_summary: true
  hourly_summary: false
  summary_time: "23:00"

google_docs:
  enabled: false  # Disable for testing
  credentials_path: "credentials.json"
  token_path: "token.json"
  folder_name: "Transcription Summaries"
  document_template: "Daily Transcript - {date}"

storage:
  base_dir: "transcripts"
  audio_dir: "audio"
  transcript_dir: "transcripts"
  summary_dir: "summaries"
  backup_dir: "backups"
  max_audio_age_days: 7
  max_transcript_age_days: 365

ui:
  system_tray: false  # Disable for testing
  auto_start: true
  notifications: false
  web_dashboard: true
  web_host: "127.0.0.1"
  web_port: 8080

debug: true
log_level: "DEBUG"